version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/www/html/logs
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=givehub
    networks:
      - givehub_network
    command: ["/var/www/html/docker-entrypoint.sh"]

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=givehub
    networks:
      - givehub_network

networks:
  givehub_network:
    driver: bridge

volumes:
  mongodb_data:
