version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4420:80"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/www/html/logs
      # Exclude vendor directory to avoid conflicts with container dependencies
      - /var/www/html/vendor
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=givehub
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_EXTENSION_MONGODB=1
    networks:
      - givehub_network

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=givehub
    networks:
      - givehub_network
    command: mongod --logpath=/var/log/mongodb/mongod.log --logappend

networks:
  givehub_network:
    driver: bridge

volumes:
  mongodb_data:
